JevonJ/Stocky

stocky-client/package.json
stocky-client/public/index.html
stocky-client/src/App.jsx
stocky-client/src/components/login/Main.css
stocky-client/src/components/login/Main.jsx
stocky-client/src/components/login/Welcome.jsx
stocky-client/src/index.js
stocky-client/yarn.lock

Add routing package

---

stocky-client/src/App.jsx
stocky-client/src/actions/PlayerActions.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/login/Host.css
stocky-client/src/components/login/Host.jsx
stocky-client/src/components/login/Lobby.jsx
stocky-client/src/components/login/Main.jsx
stocky-client/src/components/login/Welcome.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/playersReducer.js
stocky-client/src/reducers/userReducer.js
stocky-server/lib/reducers/playersReducer.js
stocky-server/lib/reducers/roomInfoReducer.js
stocky-server/lib/socketEvents.js

- Change route layout
- code clean up

Finish user game host functionality

---

stocky-client/src/components/Main.jsx
stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/SimulatorMain.jsx
stocky-client/src/reducers/userReducer.js
stocky-server/lib/socketEvents.js

Add functionality to BuyModal

---

stocky-client/src/components/modals/SellSharesModal.jsx
stocky-client/src/components/simulator/Dashboard.jsx

Add Modal for sell share

---

stocky-client/src/actions/TimeActions.js
stocky-client/src/actions/index.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/login/Lobby.jsx
stocky-client/src/components/login/Main.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/index.js
stocky-client/src/reducers/timeReducer.js
stocky-client/src/reducers/userReducer.js
stocky-server/lib/socketEvents.js

Add functionality to start the game.

---

stocky-client/src/actions/PlayerActions.js
stocky-client/src/actions/PlayerStockActions.js
stocky-client/src/actions/index.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/playerStocksReducer.js
stocky-server/lib/actions/PlayerActions.js
stocky-server/lib/actions/PlayerStockActions.js
stocky-server/lib/actions/index.js
stocky-server/lib/actions/types.js
stocky-server/lib/reducers/playerStocksReducer.js
stocky-server/lib/socketEvents.js

 Add server functions to buy stocks

---

stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PlayerList.jsx

Room members display Rank order

---

stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/modals/SellSharesModal.jsx
stocky-client/src/components/simulator/Dashboard.jsx

Add Functionality to SellSharesModal

---

stocky-client/src/actions/PlayerActions.js
stocky-client/src/actions/types.js
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/reducers/sectorStocksReducer.js
stocky-client/src/reducers/sectorsReducer.js
stocky-client/src/reducers/stocksReducer.js
stocky-server/lib/index.js
stocky-server/lib/reducers/index.js
stocky-server/lib/reducers/sectorStocksReducer.js
stocky-server/lib/reducers/sectorsReducer.js
stocky-server/lib/reducers/stocksReducer.js

Get stocks to view

---

stocky-client/src/actions/LiveFeedActions.js
stocky-client/src/actions/index.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/LiveFeed.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/index.js
stocky-client/src/reducers/liveFeedReducer.js
stocky-server/lib/reducers/roomInfoReducer.js
stocky-server/lib/socketEvents.js

Add livefeed 

---

stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PlayerList.jsx
stocky-client/src/reducers/userReducer.js
stocky-server/.eslintrc
stocky-server/lib/reducers/playerStocksReducer.js
stocky-server/lib/reducers/playersReducer.js
stocky-server/lib/socketEvents.js
stocky-server/package.json
stocky-server/yarn.lock

Order playerlist accoding to rank

---

stocky-client/src/actions/PlayerActions.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/modals/SellSharesModal.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-client/src/components/simulator/SoldStockList.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/playerStocksReducer.js
stocky-server/lib/actions/PlayerActions.js
stocky-server/lib/actions/types.js
stocky-server/lib/reducers/playerStocksReducer.js
stocky-server/lib/reducers/playersReducer.js
stocky-server/lib/socketEvents.js

Add functionlity to sell shares

---

stocky-client/src/components/login/GameList.jsx
stocky-client/src/components/login/Lobby.jsx
stocky-client/src/components/login/Main.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PlayerList.jsx
stocky-client/src/components/simulator/StockList.jsx
stocky-client/src/listeners.js
stocky-server/lib/actions/PlayerActions.js
stocky-server/lib/actions/types.js
stocky-server/lib/reducers/playerStocksReducer.js
stocky-server/lib/reducers/playersReducer.js
stocky-server/lib/reducers/roomInfoReducer.js
stocky-server/lib/reducers/roomStocksReducer.js
stocky-server/lib/socketEvents.js

Complete User join functionality

---

stocky-client/src/components/simulator/Dashboard.jsx

UI for sort stocks

---

stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-server/lib/reducers/playerStocksReducer.js

Solve purchased stock quantity does not update on sell

---

stocky-client/src/components/login/Main.jsx
stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-client/src/components/simulator/StockList.jsx
stocky-server/lib/reducers/roomStocksReducer.js

CHanges to adapt for change in stock price format

---

stocky-server/lib/actions/RoomStocksActions.js
stocky-server/lib/actions/index.js
stocky-server/lib/reducers/index.js
stocky-server/lib/reducers/trendModelReducer.js
stocky-server/lib/socketEvents.js

Add sector and market trend algorithms

---

stocky-client/src/components/login/Host.jsx

UI for choose number of rounds being the host

---

stocky-client/src/components/modals/SellSharesModal.jsx

Solve Cash Remaining & Total Assets not updating when selling stocks

---

stocky-client/.env
stocky-client/src/components/login/GameList.jsx
stocky-client/src/components/login/Host.jsx
stocky-client/src/components/login/Lobby.jsx
stocky-client/src/components/simulator/DashboarHeaderData.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-client/src/components/simulator/StockList.jsx
stocky-server/.env.default
stocky-server/lib/actions/RoomStocksActions.js
stocky-server/lib/actions/types.js
stocky-server/lib/index.js
stocky-server/lib/reducers/roomInfoReducer.js
stocky-server/lib/reducers/roomStocksReducer.js
stocky-server/lib/socketEvents.js
stocky-server/lib/stockResources.js
stocky-server/package.json
stocky-server/yarn.lock

- code refactor
- bug fixes
- issue #11

Add price fluctuations to screen

---

stocky-client/src/components/login/HowToPlay.jsx

Add UI Design for game introduction

---

stocky-client/src/components/login/Host.jsx

Add UI for input time duration for a round

---

stocky-client/package.json
stocky-client/src/actions/PlayerActions.js
stocky-client/src/actions/TimeActions.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/login/Host.jsx
stocky-client/src/components/login/HowToPlay.jsx
stocky-client/src/components/login/Lobby.jsx
stocky-client/src/components/login/Main.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/index.js
stocky-client/src/listeners.js
stocky-client/src/reducers/timeReducer.js
stocky-client/yarn.lock
stocky-server/.eslintrc
stocky-server/lib/actions/RoomStocksActions.js
stocky-server/lib/reducers/roomStocksReducer.js
stocky-server/lib/reducers/trendModelReducer.js
stocky-server/lib/socketEvents.js
stocky-server/lib/stockResources.js
stocky-server/package.json
stocky-server/yarn.lock

Add price change algorithms
UI fixes
bug fixes
Add Notification for network error
- issues #17 #67 #1

Add functionality to change rounds

---

stocky-server/lib/socketEvents.js

Modify functionality of Live Feed

---

stocky-client/src/components/simulator/PurchasedStockList.jsx

Solve Purchase quantity error

---

stocky-client/src/components/login/GameList.jsx

Code refacter UI password

---

stocky-client/src/components/login/GameList.jsx

Username issue fixed.

---

stocky-client/src/components/simulator/SoldStockList.jsx
stocky-server/lib/reducers/playerStocksReducer.js

Solve cannot sell purchases purchased in 2 rounds

---

stocky-client/src/components/login/Main.jsx

lobby scroll bar

---

stocky-client/src/actions/EventActions.js
stocky-client/src/actions/index.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/login/Host.jsx
stocky-client/src/components/simulator/CurrentEvents.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/eventsReducer.js
stocky-client/src/reducers/index.js
stocky-server/lib/reducers/roomStocksReducer.js
stocky-server/lib/reducers/trendModelReducer.js
stocky-server/lib/socketEvents.js
stocky-server/lib/stockResources.js
stocky-server/test/index.js

Add functionality to show round events
- issue #11

Add Sector and Stock event algorithms

---

stocky-client/src/components/simulator/__snapshots__/simulator.test.js.snap
stocky-client/src/components/simulator/simulator.test.js

Simulator components Renders Correctly

---

stocky-client/src/components/login/HowToPlay.jsx
stocky-client/src/components/login/Main.jsx
stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-client/src/components/simulator/StockList.jsx

Bug Fix (how to play modal, Simulator styling)

---

stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/simulator/DashboarHeaderData.jsx
stocky-client/src/components/simulator/Dashboard.jsx

Header stockvalue is not updating according to live stock value

---

stocky-client/src/components/gameSummary/StockChart.jsx
stocky-client/src/components/gameSummary/index.jsx
stocky-server/lib/reducers/roomStocksReducer.js

Add data to price fluctuation chart

---

stocky-client/src/actions/UserActions.js
stocky-client/src/actions/types.js
stocky-client/src/components/Main.jsx
stocky-client/src/components/simulator/StockList.jsx
stocky-client/src/listeners.js
stocky-client/src/reducers/userReducer.js
stocky-server/lib/index.js
stocky-server/lib/socketEvents.js

Fix issue where game stops working when Host quits

---

stocky-client/src/components/gameSummary/PlayerSummaryTable.jsx
stocky-client/src/components/gameSummary/PurchaseSummary.jsx
stocky-client/src/components/gameSummary/SoldSummary.jsx
stocky-client/src/components/gameSummary/index.jsx
stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/simulator/DashboarHeaderData.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/LiveFeed.jsx
stocky-client/src/components/simulator/PlayerList.jsx
stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-client/src/components/simulator/SoldStockList.jsx

Fixed bugs in total assets and changed some values to show decimal places

---

stocky-client/src/components/modals/BuyModalMain.jsx
stocky-client/src/components/modals/SellSharesModal.jsx
stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/PurchasedStockList.jsx
stocky-client/src/components/simulator/StockList.jsx

Simulator Bug Fixes:

---

stocky-client/src/components/simulator/Dashboard.jsx
stocky-client/src/components/simulator/SymbolLookup.jsx

Add functionality to lookup stock symbols
